// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chromaflora-homepage/LuminousDepth.tsx": () => import("../components/mockups/chromaflora-homepage/LuminousDepth.tsx"),
  "./components/mockups/chromaflora-homepage/TighterHierarchy.tsx": () => import("../components/mockups/chromaflora-homepage/TighterHierarchy.tsx")
};
